name = "vibestack-web"
compatibility_date = "2025-04-03" # Date from tutorial
assets = { not_found_handling = "single-page-application" } 
main = "./worker/index.ts" # Add main entry point for worker code 