name = "vibestack-server"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Development server configuration
[dev]
ip = "localhost"
port = 8787
local_protocol = "http"
upstream_protocol = "http"
host = "127.0.0.1"

# Environment variables
[vars]
ENVIRONMENT = "development"

# Module aliases (correct syntax)
[alias]
"debug" = "./src/shims/debug.ts"
"app-root-path" = "./src/lib/app-root-path-shim.ts"

# Specify ESM format
[build]
command = ""
watch_dir = "src"

# Durable Objects configuration
[[durable_objects.bindings]]
name = "SYNC"
class_name = "SyncDO"

[[durable_objects.bindings]]
name = "REPLICATION"
class_name = "ReplicationDO"

# Durable Objects migrations
[[migrations]]
tag = "v1"
new_classes = ["SyncDO", "ReplicationDO"]

# KV namespace configuration
[[kv_namespaces]]
binding = "CLIENT_REGISTRY"
id = "preview"
preview_id = "preview"

[env.production]
kv_namespaces = [
  { binding = "CLIENT_REGISTRY", id = "production" }
]

[env.production.vars]
ENVIRONMENT = "production"
